### ISSUE TITLE
Rust compiler version?

### ISSUE THREAD

**Issue by jpap** [dpc/rdedup#113]
I'm getting the following compilation error on beta and nightly:

```
error: expected ident, found (
   --> src/bin.rs:215:30
    |
215 |          (@arg CHUNK_SIZE: --("chunk-size") {validate_chunk_size} +takes_value "Set average chunk size"
    |                              ^

error: Could not compile `rdedup`.
```

I understand the issue is with the `clap_app` crate; but I'm not sure how to fix it without changing the argument to an unhyphenated one and dropping the parens.

What version of the compiler worked to build the codebase most recently?

**Comment by dpc** [comment]
Most probably latests are the only one being checked with 2.x.y versions. Previous versions (1.x.y) should work with stable.

**Comment by jpap** [comment]
@dpc, do you mean rustc nightly? It looks like [your Travis builds](https://github.com/dpc/rdedup/blob/master/.travis.yml) target both beta and nightly.

The above doesn't compile with nightly (1.19.0-nightly, dated 2017-06-05) or beta (1.18.0-beta.4, dated 2017-05-27).

**Comment by dpc** [comment]
```
$ rustup update
(...)
$ rustup run nightly cargo install -f rdedup
rustc 1.19.0-nightly (d015610db 2017-06-05)
$ rustup run nightly cargo install -f rdedup
(...)
Replacing /home/dpc/.cargo/bin/rdedup
$ rustup run nightly make
(...)
Finished dev [unoptimized + debuginfo] target(s) in 6.70 secs
```

Seems to work on my system: both latest release and master.

**Comment by dpc** [comment]
Beta seems fine as well.

**Comment by jpap** [comment]
Thanks for checking; I only have an issue with your last command -- to make master.  Not sure what else to try?

**Comment by dpc** [comment]
`make` -> `cargo build`

**Comment by jpap** [comment]
Works after a fresh checkout... weird?! :D

**Comment by dpc** [comment]
Are you using `CARGO_INCREMENTAL=1` maybe?
